#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0.1'
__CHEETAH_versionTuple__ = (2, 0, 1, 'final', 0)
__CHEETAH_genTime__ = 1210952453.620358
__CHEETAH_genTimestamp__ = 'Fri May 16 19:40:53 2008'
__CHEETAH_src__ = 'templates/FilesPage.tmpl'
__CHEETAH_srcLastModified__ = 'Fri May 16 19:39:13 2008'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class FilesPage(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        if len(VFFSL(SL,"summary",True)) > 0: # generated from line 1, col 1
            write('''#summary ''')
            _v = VFFSL(SL,"summary",True) # '$summary' on line 2, col 10
            if _v is not None: write(_filter(_v, rawExpr='$summary')) # from line 2, col 10.
            write('''
''')
        if len(VFFSL(SL,"labels",True)) > 0: # generated from line 4, col 1
            write('''#labels ''')
            for l in VFFSL(SL,"labels",True) : # generated from line 5, col 9
                _v = VFFSL(SL,"l",True) # '$l' on line 5, col 29
                if _v is not None: write(_filter(_v, rawExpr='$l')) # from line 5, col 29.
                write(''' ''')
            write('''
''')
        write('''
|| [''')
        _v = VFFSL(SL,"prefix",True) # '${prefix}' on line 8, col 5
        if _v is not None: write(_filter(_v, rawExpr='${prefix}')) # from line 8, col 5.
        write('''_files File List] || [''')
        _v = VFFSL(SL,"prefix",True) # '${prefix}' on line 8, col 36
        if _v is not None: write(_filter(_v, rawExpr='${prefix}')) # from line 8, col 36.
        write('''_globals Globals] ||

Here is a list of all files with brief descriptions:
''')
        for dirname, ref, pagename in VFFSL(SL,"files",True): # generated from line 11, col 1
            write('''|| ''')
            _v = VFFSL(SL,"dirname",True) # '${dirname}' on line 12, col 4
            if _v is not None: write(_filter(_v, rawExpr='${dirname}')) # from line 12, col 4.
            write('''[''')
            _v = VFFSL(SL,"prefix",True) # '${prefix}' on line 12, col 15
            if _v is not None: write(_filter(_v, rawExpr='${prefix}')) # from line 12, col 15.
            write('''_''')
            _v = VFFSL(SL,"ref",True) # '$ref' on line 12, col 25
            if _v is not None: write(_filter(_v, rawExpr='$ref')) # from line 12, col 25.
            write(''' ''')
            _v = VFFSL(SL,"pagename",True) # '$pagename' on line 12, col 30
            if _v is not None: write(_filter(_v, rawExpr='$pagename')) # from line 12, col 30.
            write('''] || ''')
            _v = VFN(VFFSL(SL,"descriptions",True),"get",False)(VFFSL(SL,"ref",True), "") # '$descriptions.get($ref, "")' on line 12, col 44
            if _v is not None: write(_filter(_v, rawExpr='$descriptions.get($ref, "")')) # from line 12, col 44.
            write(''' ||
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_FilesPage= 'respond'

## END CLASS DEFINITION

if not hasattr(FilesPage, '_initCheetahAttributes'):
    templateAPIClass = getattr(FilesPage, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(FilesPage)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=FilesPage()).run()


