#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0.1'
__CHEETAH_versionTuple__ = (2, 0, 1, 'final', 0)
__CHEETAH_genTime__ = 1210952453.597491
__CHEETAH_genTimestamp__ = 'Fri May 16 19:40:53 2008'
__CHEETAH_src__ = 'templates/Function.tmpl'
__CHEETAH_srcLastModified__ = 'Fri May 16 19:39:13 2008'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class Function(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''{{{
#''')
        _v = VFFSL(SL,"f.type",True) # '$f.type' on line 2, col 2
        if _v is not None: write(_filter(_v, rawExpr='$f.type')) # from line 2, col 2.
        write(''' ''')
        _v = VFFSL(SL,"f.name",True) # '$f.name' on line 2, col 10
        if _v is not None: write(_filter(_v, rawExpr='$f.name')) # from line 2, col 10.
        write('''   (
''')
        i = 0
        for (type, declname) in VFFSL(SL,"f.params",True): # generated from line 4, col 1
            write('''  ''')
            _v = VFFSL(SL,"type",True) # '$type' on line 5, col 3
            if _v is not None: write(_filter(_v, rawExpr='$type')) # from line 5, col 3.
            write(''' ''')
            _v = VFFSL(SL,"declname",True) # '$declname' on line 5, col 9
            if _v is not None: write(_filter(_v, rawExpr='$declname')) # from line 5, col 9.
            if VFFSL(SL,"i",True) < len(VFFSL(SL,"f.params",True)) - 1: # generated from line 6, col 1
                write(''',
''')
            i = VFFSL(SL,"i",True) + 1
        write('''  )
}}}
  ''')
        _v = VFFSL(SL,"f.brief",True) # '$f.brief' on line 13, col 3
        if _v is not None: write(_filter(_v, rawExpr='$f.brief')) # from line 13, col 3.
        write('''
  ''')
        _v = VFFSL(SL,"f.detailed",True) # '$f.detailed' on line 14, col 3
        if _v is not None: write(_filter(_v, rawExpr='$f.detailed')) # from line 14, col 3.
        write('''

''')
        if len(VFFSL(SL,"f.params",True)) > 0: # generated from line 16, col 1
            write("""*Parameters*:
  a   And two parameters. 
  b   Here's the second. 
""")
        if VFFSL(SL,"f.type",True): # generated from line 21, col 1
            write('''*Returns*:
  And a return value!
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_Function= 'respond'

## END CLASS DEFINITION

if not hasattr(Function, '_initCheetahAttributes'):
    templateAPIClass = getattr(Function, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(Function)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=Function()).run()


